### ISSUE TITLE
Launch zeitgeist standalone blockchain in docker compose

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/app-docker#2]
It should launch the Zeitgeist standalone docker image `zeitgeistpm/zeitgeist-node:v0.3.8`. We will have to manually update to the newest tags for now, maybe there is a workaround like adding a `stable` tag or something in the Zeitgeist repository. We have a `latest` tag, but it collides with Dockerhubs `latest` tag.

The docker container should:
  - Expose P2P, WS and RPC port

The node should:
  - Run in `--dev` mode
  - Make ws and rpc externally available `--ws-external --rpc-external`
  - Allow all origins `--rpc-cors all`
  - Allow unsafe rpc methods `--rpc-methods Unsafe`
  - Allow the user to specify whether the chain should be temporary or permanent. Default case should be temporary, i.e. `--tmp`. The other case could be realized via an environment variable, i.e. in case `ZEITGEIST_CHAIN_PATH` is not empty, we should use `--base-path $ZEITGEIST_CHAIN_PATH` instead of `--tmp`

**Comment by sea212** [comment]
In regards to volatility of data, it probably makes sense to sync with the devs responsible to add IPFS and Subsquid support. There could be a common solution, like ZEITGEIST_PATH and then every components just appends whatever its name is, like $ZEITGEIST_PATH/blockchain and $ZEITGEIST_PATH/subsquid.

**Comment by vivekvpandya** [comment]
Does this zeitgeistpm/zeitgeist-node:v0.3.8 provide binary or source of our node?

**Comment by sea212** [comment]
The docker image contains the binary. Running the image invokes the binary and saves the data within `/zeitgeist/data` within the docker image. See https://github.com/zeitgeistpm/zeitgeist/blob/main/Dockerfile for more information.

**Comment by sea212** [comment]
Closed by #6
